export const dom = {
    chatInput: document.querySelector('.chat-input'),
    inputWrapper: document.querySelector('.input-wrapper'),
    sendBtn: document.querySelector('.send-btn'),
    cancelBtn: document.querySelector('.cancel-btn'),
    sendCancelStack: document.querySelector('.send-cancel-stack'),
    threadList: document.querySelector('.thread-list'),
    chatMessages: document.querySelector('.chat-messages'),
    searchInput: document.querySelector('.thread-search'),
    searchBtn: document.querySelector('.search-btn'),
    searchContainer: document.querySelector('#chat-view-sidebar .sidebar-actions'),
    sidebar: document.querySelector('.sidebar'),
    sidebarResizer: document.querySelector('.sidebar-resizer'),
    workspaceSwitcher: document.querySelector('.workspace-switcher'),
    workspaceToggle: document.querySelector('.workspace-toggle'),
    workspaceToggleLabel: document.querySelector('.workspace-toggle-label'),
    workspaceDropdown: document.querySelector('.workspace-dropdown'),
    workspaceList: document.querySelector('.workspace-list'),
    workspaceSelectBtn: document.querySelector('.workspace-select-btn'),
    workspaceSearchInput: document.querySelector('.workspace-search-input'),
    modelSwitcher: document.querySelector('.model-switcher'),
    modelToggle: document.querySelector('.model-toggle'),
    modelToggleLabel: document.querySelector('.model-toggle-label'),
    modelDropdown: document.querySelector('.model-dropdown'),
    modelList: document.querySelector('.model-list'),
    modelSearchInput: document.querySelector('.model-search-input'),
    viewSwitcher: document.querySelector('.view-switcher'),
    feedTopicsList: document.querySelector('.feed-topics-list'),
    feedArticlesList: document.querySelector('.feed-articles-list'),
    feedDetailView: document.querySelector('#feed-detail-view'),
    feedBackBtn: document.querySelector('#feed-back-btn'),
    feedDetailTitle: document.querySelector('#feed-detail-title'),
    feedDetailTimestamp: document.querySelector('#feed-detail-timestamp'),
    feedDetailContent: document.querySelector('#feed-detail-content')
};
