export const state = {
    isProcessing: false,
    currentTurnContainer: null,
    currentThinkingBlock: null,
    currentThreadID: '',
    threadsCache: [],
    searchTerm: '',
    dragSourceID: '',
    workspacesCache: [],
    currentWorkspacePath: '',
    workspaceSearchTerm: '',
    modelsCache: [],
    modelSearchTerm: '',
    currentModelID: '',
    thinkingStartTime: 0,
    thinkingTimerInterval: null,
    currentToolCallElements: new Map(),
    toolTimerIntervals: new Map(),
    lastThoughtText: '',
    lastThoughtElement: null,
    lastThinkingDuration: null,
    // Typewriter effect state
    pendingStreamBuffer: '',
    isStreamingLoopActive: false,
    pendingThinkingBuffer: '',
    isThinkingLoopActive: false,
    
    lastAssistantTurnIndex: -1,
    cancelHandled: false,
    cancelVisible: false,
    isComposing: false,
    suppressEnterOnce: false,
    isLoadingHistory: false,
    loadSequence: 0,
    activeLoadToken: 0,
    activeLoadThreadID: '',
    userMessageCount: 0,
    pendingRegenerateContext: null,
    userMessageCache: [],
    turnRegenerateContext: new Map(),
    pendingAgentMessages: [],
    feedTopicsCache: [],
    feedArticlesCache: [],
    currentFeedTopicId: '',
    feedTopicsLoading: false,
    feedArticlesLoading: false,
    feedTopicsError: '',
    feedArticlesError: '',
    feedArticlesRequestToken: 0
};
